/********************************************************************
* TRinsideCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TRinsideCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRinsideCint();
extern void G__cpp_setup_inheritanceTRinsideCint();
extern void G__cpp_setup_typetableTRinsideCint();
extern void G__cpp_setup_memvarTRinsideCint();
extern void G__cpp_setup_globalTRinsideCint();
extern void G__cpp_setup_memfuncTRinsideCint();
extern void G__cpp_setup_funcTRinsideCint();
extern void G__set_cpp_environmentTRinsideCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TRinside.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRinsideCintLN_TClass;
extern G__linked_taginfo G__TRinsideCintLN_TBuffer;
extern G__linked_taginfo G__TRinsideCintLN_TMemberInspector;
extern G__linked_taginfo G__TRinsideCintLN_TObject;
extern G__linked_taginfo G__TRinsideCintLN_ROOT;
extern G__linked_taginfo G__TRinsideCintLN_string;
extern G__linked_taginfo G__TRinsideCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TRinsideCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRinsideCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TRinsideCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRinsideCintLN_TArrayD;
extern G__linked_taginfo G__TRinsideCintLN_RInside;
extern G__linked_taginfo G__TRinsideCintLN_ROOTcLcLR;
extern G__linked_taginfo G__TRinsideCintLN_ROOTcLcLRcLcLTRinside;

/* STUB derived class for protected member access */
