//
// File generated by rootcint at Sun Apr 14 15:01:31 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TRinsideCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TRinsideCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void ROOTcLcLRcLcLTRinside_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_ROOTcLcLRcLcLTRinside(void *p);
   static void deleteArray_ROOTcLcLRcLcLTRinside(void *p);
   static void destruct_ROOTcLcLRcLcLTRinside(void *p);
   static void streamer_ROOTcLcLRcLcLTRinside(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ROOT::R::TRinside*)
   {
      ::ROOT::R::TRinside *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ROOT::R::TRinside >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ROOT::R::TRinside", ::ROOT::R::TRinside::Class_Version(), "./TRinside.h", 34,
                  typeid(::ROOT::R::TRinside), DefineBehavior(ptr, ptr),
                  &::ROOT::R::TRinside::Dictionary, isa_proxy, 16,
                  sizeof(::ROOT::R::TRinside) );
      instance.SetDelete(&delete_ROOTcLcLRcLcLTRinside);
      instance.SetDeleteArray(&deleteArray_ROOTcLcLRcLcLTRinside);
      instance.SetDestructor(&destruct_ROOTcLcLRcLcLTRinside);
      instance.SetStreamerFunc(&streamer_ROOTcLcLRcLcLTRinside);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ROOT::R::TRinside*)
   {
      return GenerateInitInstanceLocal((::ROOT::R::TRinside*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ROOT::R::TRinside*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

      namespace ROOT {
         namespace R {
//______________________________________________________________________________
TClass *TRinside::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TRinside::Class_Name()
{
   return "ROOT::R::TRinside";
}

//______________________________________________________________________________
const char *TRinside::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ROOT::R::TRinside*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TRinside::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ROOT::R::TRinside*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TRinside::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ROOT::R::TRinside*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TRinside::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ROOT::R::TRinside*)0x0)->GetClass();
   return fgIsA;
}

} // namespace ROOT::R
} // namespace ROOT::R
      namespace ROOT {
         namespace R {
//______________________________________________________________________________
void TRinside::Streamer(TBuffer &R__b)
{
   // Stream an object of class ROOT::R::TRinside.

   //This works around a msvc bug and should be harmless on other platforms
   typedef ::ROOT::R::TRinside thisClass;
   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> R;
      R__b.CheckByteCount(R__s, R__c, thisClass::IsA());
   } else {
      R__c = R__b.WriteVersion(thisClass::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << R;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

} // namespace ROOT::R
} // namespace ROOT::R
//______________________________________________________________________________
      namespace ROOT {
         namespace R {
void TRinside::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ROOT::R::TRinside.
      TClass *R__cl = ::ROOT::R::TRinside::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*R", &R);
      TObject::ShowMembers(R__insp);
}

} // namespace ROOT::R
} // namespace ROOT::R
namespace ROOT {
   // Wrapper around operator delete
   static void delete_ROOTcLcLRcLcLTRinside(void *p) {
      delete ((::ROOT::R::TRinside*)p);
   }
   static void deleteArray_ROOTcLcLRcLcLTRinside(void *p) {
      delete [] ((::ROOT::R::TRinside*)p);
   }
   static void destruct_ROOTcLcLRcLcLTRinside(void *p) {
      typedef ::ROOT::R::TRinside current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_ROOTcLcLRcLcLTRinside(TBuffer &buf, void *obj) {
      ((::ROOT::R::TRinside*)obj)->::ROOT::R::TRinside::Streamer(buf);
   }
} // end of namespace ROOT for class ::ROOT::R::TRinside

/********************************************************
* TRinsideCint.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTRinsideCint();

extern "C" void G__set_cpp_environmentTRinsideCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TRinside.h");
  G__cpp_reset_tagtableTRinsideCint();
}
#include <new>
extern "C" int G__cpp_dllrevTRinsideCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ROOT::R::TRinside */
static int G__TRinsideCint_174_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ROOT::R::TRinside* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 5:
     //m: 5
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ROOT::R::TRinside(
(const int) G__int(libp->para[0]), (const char* *const) G__int(libp->para[1])
, (const bool) G__int(libp->para[2]), (const bool) G__int(libp->para[3])
, (const bool) G__int(libp->para[4]));
     } else {
       p = new((void*) gvp) ROOT::R::TRinside(
(const int) G__int(libp->para[0]), (const char* *const) G__int(libp->para[1])
, (const bool) G__int(libp->para[2]), (const bool) G__int(libp->para[3])
, (const bool) G__int(libp->para[4]));
     }
     break;
   case 4:
     //m: 4
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ROOT::R::TRinside(
(const int) G__int(libp->para[0]), (const char* *const) G__int(libp->para[1])
, (const bool) G__int(libp->para[2]), (const bool) G__int(libp->para[3]));
     } else {
       p = new((void*) gvp) ROOT::R::TRinside(
(const int) G__int(libp->para[0]), (const char* *const) G__int(libp->para[1])
, (const bool) G__int(libp->para[2]), (const bool) G__int(libp->para[3]));
     }
     break;
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ROOT::R::TRinside(
(const int) G__int(libp->para[0]), (const char* *const) G__int(libp->para[1])
, (const bool) G__int(libp->para[2]));
     } else {
       p = new((void*) gvp) ROOT::R::TRinside(
(const int) G__int(libp->para[0]), (const char* *const) G__int(libp->para[1])
, (const bool) G__int(libp->para[2]));
     }
     break;
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ROOT::R::TRinside((const int) G__int(libp->para[0]), (const char* *const) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) ROOT::R::TRinside((const int) G__int(libp->para[0]), (const char* *const) G__int(libp->para[1]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TRinsideCintLN_ROOTcLcLRcLcLTRinside));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TRinsideCint_174_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ROOT::R::TRinside*) G__getstructoffset())->parseEvalQ(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TRinsideCint_174_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ROOT::R::TRinside::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TRinsideCint_174_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ROOT::R::TRinside::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TRinsideCint_174_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ROOT::R::TRinside::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TRinsideCint_174_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ROOT::R::TRinside::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TRinsideCint_174_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ROOT::R::TRinside*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TRinsideCint_174_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ROOT::R::TRinside::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TRinsideCint_174_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ROOT::R::TRinside::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TRinsideCint_174_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ROOT::R::TRinside::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TRinsideCint_174_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ROOT::R::TRinside::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TRinsideCint_174_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ROOT::R::TRinside*) G__getstructoffset())->assign(*(TArrayD*) libp->para[0].ref, *(string*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TRinsideCint_174_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ROOT::R::TRinside*) G__getstructoffset())->assign(*(Rcpp::InternalFunction*) libp->para[0].ref, *(string*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TRinsideCint_174_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ROOT::R::TRinside* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ROOT::R::TRinside(*(ROOT::R::TRinside*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TRinsideCintLN_ROOTcLcLRcLcLTRinside));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ROOT::R::TRinside G__TROOTcLcLRcLcLTRinside;
static int G__TRinsideCint_174_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ROOT::R::TRinside*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ROOT::R::TRinside*) (soff+(sizeof(ROOT::R::TRinside)*i)))->~G__TROOTcLcLRcLcLTRinside();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ROOT::R::TRinside*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ROOT::R::TRinside*) (soff))->~G__TROOTcLcLRcLcLTRinside();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TRinsideCint_174_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ROOT::R::TRinside* dest = (ROOT::R::TRinside*) G__getstructoffset();
   *dest = *(ROOT::R::TRinside*) libp->para[0].ref;
   const ROOT::R::TRinside& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ROOT::R::TRinside */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTRinsideCint {
 public:
  G__Sizep2memfuncTRinsideCint(): p(&G__Sizep2memfuncTRinsideCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTRinsideCint::*p)();
};

size_t G__get_sizep2memfuncTRinsideCint()
{
  G__Sizep2memfuncTRinsideCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTRinsideCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TRinsideCintLN_ROOTcLcLRcLcLTRinside))) {
     ROOT::R::TRinside *G__Lderived;
     G__Lderived=(ROOT::R::TRinside*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TRinsideCintLN_ROOTcLcLRcLcLTRinside),G__get_linked_tagnum(&G__TRinsideCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTRinsideCint() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TRinsideCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TRinsideCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TRinsideCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TRinsideCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TRinsideCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TRinsideCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TRinsideCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TRinsideCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TRinsideCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TRinsideCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ROOT::R::TRinside */
static void G__setup_memvarROOTcLcLRcLcLTRinside(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TRinsideCintLN_ROOTcLcLRcLcLTRinside));
   { ROOT::R::TRinside *p; p=(ROOT::R::TRinside*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TRinsideCintLN_RInside),-1,-1,4,"R=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TRinsideCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTRinsideCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncROOTcLcLRcLcLTRinside(void) {
   /* ROOT::R::TRinside */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TRinsideCintLN_ROOTcLcLRcLcLTRinside));
   G__memfunc_setup("TRinside",802,G__TRinsideCint_174_0_1, 105, G__get_linked_tagnum(&G__TRinsideCintLN_ROOTcLcLRcLcLTRinside), -1, 0, 5, 1, 1, 0, 
"i - - 10 - argc C - - 52 - argv "
"g - - 10 'false' loadRcpp g - - 10 'false' verbose "
"g - - 10 'false' interactive", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("parseEvalQ",1012,G__TRinsideCint_174_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - code", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TRinsideCint_174_0_3, 85, G__get_linked_tagnum(&G__TRinsideCintLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ROOT::R::TRinside::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TRinsideCint_174_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ROOT::R::TRinside::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TRinsideCint_174_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ROOT::R::TRinside::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TRinsideCint_174_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ROOT::R::TRinside::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TRinsideCintLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TRinsideCint_174_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TRinsideCint_174_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ROOT::R::TRinside::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TRinsideCint_174_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ROOT::R::TRinside::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TRinsideCint_174_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ROOT::R::TRinside::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TRinsideCint_174_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ROOT::R::TRinside::DeclFileLine) ), 0);
   G__memfunc_setup("assign",645,G__TRinsideCint_174_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TArrayD' - 11 - obj u 'string' - 11 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("assign",645,G__TRinsideCint_174_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'Rcpp::InternalFunction' - 11 - obj u 'string' - 11 - name", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("TRinside", 802, G__TRinsideCint_174_0_17, (int) ('i'), G__get_linked_tagnum(&G__TRinsideCintLN_ROOTcLcLRcLcLTRinside), -1, 0, 1, 1, 1, 0, "u 'ROOT::R::TRinside' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TRinside", 928, G__TRinsideCint_174_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TRinsideCint_174_0_19, (int) ('u'), G__get_linked_tagnum(&G__TRinsideCintLN_ROOTcLcLRcLcLTRinside), -1, 1, 1, 1, 1, 0, "u 'ROOT::R::TRinside' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTRinsideCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTRinsideCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTRinsideCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TRinsideCintLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TRinsideCintLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TRinsideCintLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TRinsideCintLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TRinsideCintLN_ROOT = { "ROOT" , 110 , -1 };
G__linked_taginfo G__TRinsideCintLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__TRinsideCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TRinsideCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TRinsideCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TRinsideCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TRinsideCintLN_TArrayD = { "TArrayD" , 99 , -1 };
G__linked_taginfo G__TRinsideCintLN_RInside = { "RInside" , 99 , -1 };
G__linked_taginfo G__TRinsideCintLN_Rcpp = { "Rcpp" , 110 , -1 };
G__linked_taginfo G__TRinsideCintLN_RcppcLcLInternalFunction = { "Rcpp::InternalFunction" , 99 , -1 };
G__linked_taginfo G__TRinsideCintLN_ROOTcLcLR = { "ROOT::R" , 110 , -1 };
G__linked_taginfo G__TRinsideCintLN_ROOTcLcLRcLcLTRinside = { "ROOT::R::TRinside" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTRinsideCint() {
  G__TRinsideCintLN_TClass.tagnum = -1 ;
  G__TRinsideCintLN_TBuffer.tagnum = -1 ;
  G__TRinsideCintLN_TMemberInspector.tagnum = -1 ;
  G__TRinsideCintLN_TObject.tagnum = -1 ;
  G__TRinsideCintLN_ROOT.tagnum = -1 ;
  G__TRinsideCintLN_string.tagnum = -1 ;
  G__TRinsideCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TRinsideCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TRinsideCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TRinsideCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TRinsideCintLN_TArrayD.tagnum = -1 ;
  G__TRinsideCintLN_RInside.tagnum = -1 ;
  G__TRinsideCintLN_Rcpp.tagnum = -1 ;
  G__TRinsideCintLN_RcppcLcLInternalFunction.tagnum = -1 ;
  G__TRinsideCintLN_ROOTcLcLR.tagnum = -1 ;
  G__TRinsideCintLN_ROOTcLcLRcLcLTRinside.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTRinsideCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_TClass);
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_TObject);
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_ROOT);
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_string);
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_TArrayD);
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_RInside);
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_Rcpp);
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_RcppcLcLInternalFunction);
   G__get_linked_tagnum_fwd(&G__TRinsideCintLN_ROOTcLcLR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TRinsideCintLN_ROOTcLcLRcLcLTRinside),sizeof(ROOT::R::TRinside),-1,62464,(char*)NULL,G__setup_memvarROOTcLcLRcLcLTRinside,G__setup_memfuncROOTcLcLRcLcLTRinside);
}
extern "C" void G__cpp_setupTRinsideCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupTRinsideCint()");
  G__set_cpp_environmentTRinsideCint();
  G__cpp_setup_tagtableTRinsideCint();

  G__cpp_setup_inheritanceTRinsideCint();

  G__cpp_setup_typetableTRinsideCint();

  G__cpp_setup_memvarTRinsideCint();

  G__cpp_setup_memfuncTRinsideCint();
  G__cpp_setup_globalTRinsideCint();
  G__cpp_setup_funcTRinsideCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTRinsideCint();
  return;
}
class G__cpp_setup_initTRinsideCint {
  public:
    G__cpp_setup_initTRinsideCint() { G__add_setup_func("TRinsideCint",(G__incsetup)(&G__cpp_setupTRinsideCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTRinsideCint() { G__remove_setup_func("TRinsideCint"); }
};
G__cpp_setup_initTRinsideCint G__cpp_setup_initializerTRinsideCint;

